github: [metadata]
title: DHE Modules
description: VCV Rack modules from Dale Emery
theme: jekyll-theme-slate
show_downloads: false
incremental: false
permalink: pretty
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
baseurl: /DHE-Modules
